# Generated by Django 4.1 on 2022-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
