# Generated by Django 4.1 on 2022-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacy_address_pharmacy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
