# Generated by Django 4.1 on 2022-10-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmacy_address_alter_pharmacy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.TextField(),
        ),
    ]
