# Generated by Django 4.1 on 2022-10-28 15:35

from django.db import migrations

def add_app_admin_role(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Medicine = apps.get_model('medicine', 'Medicine')
    app_admin_group, created = Group.objects.get_or_create(name='app_admin')
    content_type = ContentType.objects.get_for_model(Medicine)
    permissions = list(Permission.objects.filter(content_type=content_type))
    app_admin_group.permissions.set(permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_app_admin_role)
    ]
