# Generated by Django 4.1 on 2022-11-01 14:58

from django.db import migrations

def add_customer_role(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group, created = Group.objects.get_or_create(name='customer')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_authorize_pharmacy_to_admin'),
    ]

    operations = [
        migrations.RunPython(add_customer_role)
    ]
