# Generated by Django 4.1 on 2022-11-02 10:20

from django.db import migrations

def add_customer_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get(name='customer')
    
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Customer = apps.get_model('customer', 'Customer')
    content_type = ContentType.objects.get_for_model(Customer)

    Permission = apps.get_model('auth', 'Permission')
    permissions = list(Permission.objects.filter(content_type=content_type))
    for permission in permissions:
        group.permissions.add(permission)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_role'),
    ]

    operations = [
        migrations.RunPython(add_customer_perms)
    ]
